# Generated by Django 6.0.1 on 2026-01-26 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_reconocimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datospersonales',
            old_name='direccion',
            new_name='direccion_domiciliaria',
        ),
        migrations.RenameField(
            model_name='datospersonales',
            old_name='telefono',
            new_name='telefono_convencional',
        ),
        migrations.RenameField(
            model_name='reconocimiento',
            old_name='institucion',
            new_name='contacto',
        ),
        migrations.RemoveField(
            model_name='reconocimiento',
            name='titulo',
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='direccion_trabajo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='licencia_conducir',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='perfil_activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='telefono_fijo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='certificado',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='contacto_empresa',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='email_empresa',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='lugar_empresa',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='web_empresa',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='certificado',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='entidad',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Académico', 'Académico'), ('Público', 'Público'), ('Privado', 'Privado')], max_length=50),
        ),
    ]
