# Generated by Django 6.0.1 on 2026-01-27 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_rename_direccion_datospersonales_direccion_domiciliaria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='perfil',
        ),
        migrations.DeleteModel(
            name='Lenguaje',
        ),
        migrations.DeleteModel(
            name='Proyecto',
        ),
    ]
