# Generated by Django 6.0.1 on 2026-01-27 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_proyecto_perfil_delete_lenguaje_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='perfil',
        ),
        migrations.RemoveField(
            model_name='reconocimiento',
            name='perfil',
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='estado_civil',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='lugar_nacimiento',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='nacionalidad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='numero_cedula',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='sexo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CursosRealizados',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_curso', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('total_horas', models.PositiveIntegerField()),
                ('descripcion', models.TextField(blank=True)),
                ('entidad', models.CharField(blank=True, max_length=200)),
                ('contacto', models.CharField(blank=True, max_length=200)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20)),
                ('email_empresa', models.EmailField(blank=True, max_length=254)),
                ('activo', models.BooleanField(default=True)),
                ('certificado', models.URLField(blank=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_realizados', to='tasks.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='ProductosAcademicos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_recurso', models.CharField(max_length=200)),
                ('clasificador', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_academicos', to='tasks.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Reconocimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(blank=True)),
                ('entidad', models.CharField(blank=True, max_length=200)),
                ('contacto', models.CharField(blank=True, max_length=200)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('certificado', models.URLField(blank=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconocimientos', to='tasks.perfil')),
            ],
        ),
        migrations.DeleteModel(
            name='Educacion',
        ),
        migrations.DeleteModel(
            name='ExperienciaLaboral',
        ),
        migrations.DeleteModel(
            name='Reconocimiento',
        ),
    ]
