# Generated by Django 6.0.1 on 2026-01-27 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_experiencialaboral_perfil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='github',
        ),
    ]
