# Generated by Django 6.0.1 on 2026-01-27 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_perfil_github'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosLaborales',
            fields=[
                ('id_producto_laboral', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=200)),
                ('fecha_producto', models.DateField()),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_laborales', to='tasks.perfil')),
            ],
        ),
    ]
