# Generated by Django 6.0.1 on 2026-01-27 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_productoslaborales'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaGarage',
            fields=[
                ('id_venta_garage', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=200)),
                ('estado_producto', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular')], max_length=50)),
                ('fecha_producto', models.DateField()),
                ('descripcion', models.TextField(blank=True)),
                ('valor_bien', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venta_garage', to='tasks.perfil')),
            ],
        ),
    ]
