# Generated by Django 6.0.1 on 2026-01-27 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_ventagarage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reconocimientos',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ventagarage',
            name='fecha_producto',
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='apellidos',
            field=models.CharField(default='Sin definir', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='descripcion_perfil',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='nombres',
            field=models.CharField(default='Sin definir', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reconocimientos',
            name='id_reconocimiento',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='entidad',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='lugar_nacimiento',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='sexo',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='entidad',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='tipo',
            field=models.CharField(choices=[('Académico', 'Académico'), ('Público', 'Público'), ('Privado', 'Privado')], max_length=50),
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id_experiencia', models.AutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=200)),
                ('empresa', models.CharField(max_length=200)),
                ('lugar_empresa', models.CharField(max_length=200)),
                ('email_empresa', models.EmailField(blank=True, max_length=254)),
                ('sitio_web_empresa', models.URLField(blank=True)),
                ('contacto_empresa', models.CharField(blank=True, max_length=200)),
                ('telefono_contacto_empresa', models.CharField(blank=True, max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('descripcion_funciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('certificado', models.URLField(blank=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencia_laboral', to='tasks.perfil')),
            ],
        ),
    ]
