# Generated by Django 6.0.1 on 2026-01-28 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_remove_reconocimientos_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productosacademicos',
            name='perfil',
        ),
        migrations.RemoveField(
            model_name='productoslaborales',
            name='perfil',
        ),
        migrations.RemoveField(
            model_name='reconocimientos',
            name='perfil',
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='apellidos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='descripcion_perfil',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='direccion_domiciliaria',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='direccion_trabajo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='nombres',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='numero_cedula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='sexo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='sitio_web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='telefono_convencional',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='telefono_fijo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='cargo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='certificado',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='contacto_empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='descripcion_funciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='email_empresa',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='empresa',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='lugar_empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='sitio_web_empresa',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='telefono_contacto_empresa',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='pais',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='estado_producto',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='CursoRealizado',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_curso', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('total_horas', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('entidad', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
                ('telefono_contacto', models.CharField(max_length=20)),
                ('email_empresa', models.EmailField(max_length=254)),
                ('activo', models.BooleanField(default=True)),
                ('certificado', models.URLField(blank=True, null=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_realizados', to='tasks.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoAcademico',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_recurso', models.CharField(max_length=200)),
                ('clasificador', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_academicos', to='tasks.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoLaboral',
            fields=[
                ('id_producto_laboral', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=200)),
                ('fecha_producto', models.DateField()),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_laborales', to='tasks.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Reconocimiento',
            fields=[
                ('id_reconocimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('entidad', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
                ('telefono_contacto', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('certificado', models.URLField(blank=True, null=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconocimientos', to='tasks.perfil')),
            ],
        ),
        migrations.DeleteModel(
            name='CursosRealizados',
        ),
        migrations.DeleteModel(
            name='ProductosAcademicos',
        ),
        migrations.DeleteModel(
            name='ProductosLaborales',
        ),
        migrations.DeleteModel(
            name='Reconocimientos',
        ),
    ]
