# Generated by Django 6.0.1 on 2026-01-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_remove_productosacademicos_perfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursorealizado',
            name='certificado',
            field=models.FileField(blank=True, null=True, upload_to='certificados/'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='sexo',
            field=models.CharField(blank=True, choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='certificado',
            field=models.FileField(blank=True, null=True, upload_to='certificados/'),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='certificado',
            field=models.FileField(blank=True, null=True, upload_to='certificados/'),
        ),
    ]
