# Generated by Django 6.0.1 on 2026-01-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_cursorealizado_certificado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursorealizado',
            name='certificado_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='certificado_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='certificado_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
