# Generated by Django 6.0.1 on 2026-01-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_cursorealizado_certificado_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursorealizado',
            name='id_curso',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='id_experiencia',
        ),
        migrations.RemoveField(
            model_name='productoacademico',
            name='id_producto',
        ),
        migrations.RemoveField(
            model_name='productolaboral',
            name='id_producto_laboral',
        ),
        migrations.RemoveField(
            model_name='reconocimiento',
            name='id_reconocimiento',
        ),
        migrations.RemoveField(
            model_name='ventagarage',
            name='id_venta_garage',
        ),
        migrations.AddField(
            model_name='cursorealizado',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='productoacademico',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='productolaboral',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='ventagarage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
