# Generated by Django 6.0.1 on 2026-01-28 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_remove_cursorealizado_id_curso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursorealizado',
            name='contacto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cursorealizado',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cursorealizado',
            name='email_empresa',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='cursorealizado',
            name='entidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cursorealizado',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cursorealizado',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cursorealizado',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cursorealizado',
            name='total_horas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productoacademico',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productolaboral',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productolaboral',
            name='fecha_producto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='contacto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='entidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
