# Generated by Django 6.0.1 on 2026-01-29 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_alter_cursorealizado_contacto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursorealizado',
            name='total_horas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
