# Generated by Django 6.0.1 on 2026-01-29 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_alter_cursorealizado_total_horas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursorealizado',
            name='certificado_url',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='certificado_url',
        ),
        migrations.RemoveField(
            model_name='reconocimiento',
            name='certificado_url',
        ),
        migrations.AlterField(
            model_name='cursorealizado',
            name='certificado',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cursorealizado',
            name='nombre_curso',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cursorealizado',
            name='total_horas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='sexo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='certificado',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productoacademico',
            name='clasificador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productoacademico',
            name='nombre_recurso',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productolaboral',
            name='nombre_producto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='certificado',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='estado_producto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='nombre_producto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='valor_bien',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
