# Generated by Django 6.0.1 on 2026-01-30 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_remove_cursorealizado_certificado_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='apellidos',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nombres',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='biografia',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='pais',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
