# Generated by Django 6.0.1 on 2026-01-30 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_perfil_apellidos_perfil_nombres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursorealizado',
            name='certificado_archivo',
            field=models.FileField(blank=True, null=True, upload_to='certificados/'),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='certificado_archivo',
            field=models.FileField(blank=True, null=True, upload_to='certificados/'),
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='certificado_archivo',
            field=models.FileField(blank=True, null=True, upload_to='certificados/'),
        ),
    ]
