# Generated by Django 6.0.1 on 2026-02-03 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_cursorealizado_certificado_archivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventagarage',
            name='foto_producto',
            field=models.ImageField(blank=True, null=True, upload_to='garage/', verbose_name='Foto del Producto'),
        ),
    ]
